# 1. Base image ufficiale Node.js LTS
FROM node:24 AS build

# 2. Imposta la cartella di lavoro dentro il container
WORKDIR /app

# 3. Copia i file package.json e package-lock.json
#    serve per installare le dipendenze prima di copiare tutto il codice
COPY package*.json ./

# 4. Installa le dipendenze Node
RUN npm install

# 5. Copia tutto il codice del frontend dentro il container
COPY . .

# 6. Build produzione Angular
RUN npm run build --prod

# 7
FROM nginx:alpine

# 8
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html

# 9. Espone la porta che useremo
EXPOSE 80

# 10. Comando di avvio del frontend
CMD ["nginx", "-g", "daemon off;"]